### ISSUE TITLE
Flicker issue?

### ISSUE THREAD

**Issue by FTCodex** [JoseRFelix/react-css-theme-switcher#11]
I have followed your docs but I have a flicker issue when using with Antd library. I'm not sure what could be the cause of it. Would it be because there's a delay loading the switched theme file and it is applied once it's loaded, if so how can I sync everything together?

![Flicker](https://user-images.githubusercontent.com/72392212/99152973-3ff9f980-269d-11eb-916f-d0f060217826.gif)

```
    <Layout>
      <Header
        style={{
          position: "fixed",
          zIndex: 1,
          width: "100%",
          padding: "0 28px",
        }}
      >
        <Row
          type="flex"
          justify="space-between"
          align="middle"
          style={{ height: "100%" }}
        >
          <Col>
            <Title level={3} style={{ margin: 0 }}>
              Chats
            </Title>
          </Col>
          <Col>
            <Toggle />
          </Col>
        </Row>
      </Header>
      <Content
        style={{
          marginTop: 57,
          height: "calc(100vh - 57px)",
        }}
      ></Content>
    </Layout>
```

```
const Toggle = () => {
  const dispatch = useDispatch();
  const mode = useSelector(currentMode);
  const { switcher, status, themes } = useThemeSwitcher();

  const handleChange = () => {
    dispatch(onChangeMode());
    switcher({ theme: mode ? themes.light : themes.dark });
  };

  // Avoid theme change flicker
  if (status === "loading") {
    return null;
  }

  return <Switch checked={mode} onChange={handleChange} />;
};
```

**Comment by JoseRFelix** [comment]
There is going to be a flicker since you are returning a null element that unmounts all consequent elements. A loading screen could help greatly.

Also, are you loading fonts from an external CDN like Google Fonts? If so, it may be responsible for the font flickering.

**Comment by FTCodex** [comment]
> There is going to be a flicker since you are returning a null element that unmounts all consequent elements. A loading screen could help greatly.
> 
> Also, are you loading fonts from an external CDN like Google Fonts? If so, it may be responsible for the font flickering.

Great thank you, I just made a conditional statement to not display layout on Loading status seems to have fixed my issue. This is a great piece of kit thanks for your reply!
