### ISSUE TITLE
data-theme doesnt change correctly

### ISSUE THREAD

**Issue by dukesx** [JoseRFelix/react-css-theme-switcher#12]
I am trying to use this package with use-dark-mode in Next-JS. I need to switch between light and dark mode. Here's a brief mechanism of how this works:

1. use-dark-mode fetches value from local state for theme, it passes that to "value" argument in REACT HOOK
2. This "value" is used as a boolean, if true, switch to dark else keep light theme.

Problem: When i switch between light or dark mode, data-theme="light" or data-theme="dark" just gets stuck. Lets suppose, i am on light mode. i click switch to dark, the data-theme attribute doesn't change value from light to dark. No matter how many times i click it.

**Comment by JoseRFelix** [comment]
Can you reproduce it in a new repo? I would appreciate it, so I can fix it quickly if needed.

**Comment by dukesx** [comment]
> Can you reproduce it in a new repo? I would appreciate it, so I can fix it quickly if needed.

Here, https://github.com/dukesx/css-theme-switcher-sample

Files to check 
- _app.js
- components/global/nav.js

use-dark-mode supports SSR, exposes "value", "enable", "disable" from useDarkMode() hook. Value is fetched fist from system UI otherwise from localstorage key called "darkMode"

Just run project using "npm run dev"

**Comment by JoseRFelix** [comment]
Ok, I solved it. Add this to `wrapper.js`

```
import { useEffect } from "react";
import { useThemeSwitcher } from "react-css-theme-switcher";
import { Layout } from "antd";

import Nav from "./nav";
import useDarkMode from "use-dark-mode";

const Wrapper = (props) => {
  const { currentTheme, status, switcher } = useThemeSwitcher();
  const { value: isDarkMode } = useDarkMode();

  useEffect(() => {
    if (isDarkMode) {
      switcher("dark");
    } else {
      switcher("light");
    }
  }, [isDarkMode]);

  if (status === "loading") {
    return null;
  }
  return (
    <>
      <Nav theme={currentTheme} />
      <Layout.Content className="">{props.children}</Layout.Content>
    </>
  );
};

export default Wrapper;
```

And to `_app.js`

```
import "styles/index.scss";
import React from "react";
import Head from "next/head";
import { ApolloProvider } from "@apollo/client";
import { useApollo } from "../lib/apolloClient";
import useDarkMode from "use-dark-mode";
import { createStore, StoreProvider } from "easy-peasy";
import { Global } from "../store/global";
import "remixicon/fonts/remixicon.css";
import { Provider } from "next-auth/client";
import { ThemeSwitcherProvider } from "react-css-theme-switcher";
import "lib/plugins/embeds/style.css";
import "lib/plugins/unsplash/style.css";
import "styles/custom.scss";

const themes = {
  dark: `/dark-theme.css`,
  light: `/light-theme.css`,
};

const store = createStore(Global);
function MyApp({ Component, pageProps }) {
  const apolloClient = useApollo(pageProps.initialApolloState);
  const { value: isDarkMode } = useDarkMode(false, {
    classNameDark: "dark",
  });

  return (
    <>
      <Head>
        <title>My page</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
      </Head>
      <StoreProvider store={store}>
        <ApolloProvider client={apolloClient}>
          <ThemeSwitcherProvider
            themeMap={themes}
            defaultTheme={isDarkMode ? "dark" : "light"}
          >
            <Provider session={pageProps.session}>
              <Component {...pageProps} />
            </Provider>
          </ThemeSwitcherProvider>
        </ApolloProvider>
      </StoreProvider>
    </>
  );
}

export default MyApp;
```

What happens is that `defaultTheme` is only evaluated once. In order to change the theme, one must use an effect to react to the value change and trigger a change in `react-css-theme-switcher`

Cheers 🚀

**Comment by dukesx** [comment]
> Ok, I solved it. Add this to `wrapper.js`
> 
> ```
> import { useEffect } from "react";
> import { useThemeSwitcher } from "react-css-theme-switcher";
> import { Layout } from "antd";
> 
> import Nav from "./nav";
> import useDarkMode from "use-dark-mode";
> 
> const Wrapper = (props) => {
>   const { currentTheme, status, switcher } = useThemeSwitcher();
>   const { value: isDarkMode } = useDarkMode();
> 
>   useEffect(() => {
>     if (isDarkMode) {
>       switcher("dark");
>     } else {
>       switcher("light");
>     }
>   }, [isDarkMode]);
> 
>   if (status === "loading") {
>     return null;
>   }
>   return (
>     <>
>       <Nav theme={currentTheme} />
>       <Layout.Content className="">{props.children}</Layout.Content>
>     </>
>   );
> };
> 
> export default Wrapper;
> ```
> 
> And to `_app.js`
> 
> ```
> import "styles/index.scss";
> import React from "react";
> import Head from "next/head";
> import { ApolloProvider } from "@apollo/client";
> import { useApollo } from "../lib/apolloClient";
> import useDarkMode from "use-dark-mode";
> import { createStore, StoreProvider } from "easy-peasy";
> import { Global } from "../store/global";
> import "remixicon/fonts/remixicon.css";
> import { Provider } from "next-auth/client";
> import { ThemeSwitcherProvider } from "react-css-theme-switcher";
> import "lib/plugins/embeds/style.css";
> import "lib/plugins/unsplash/style.css";
> import "styles/custom.scss";
> 
> const themes = {
>   dark: `/dark-theme.css`,
>   light: `/light-theme.css`,
> };
> 
> const store = createStore(Global);
> function MyApp({ Component, pageProps }) {
>   const apolloClient = useApollo(pageProps.initialApolloState);
>   const { value: isDarkMode } = useDarkMode(false, {
>     classNameDark: "dark",
>   });
> 
>   return (
>     <>
>       <Head>
>         <title>My page</title>
>         <meta
>           name="viewport"
>           content="minimum-scale=1, initial-scale=1, width=device-width"
>         />
>       </Head>
>       <StoreProvider store={store}>
>         <ApolloProvider client={apolloClient}>
>           <ThemeSwitcherProvider
>             themeMap={themes}
>             defaultTheme={isDarkMode ? "dark" : "light"}
>           >
>             <Provider session={pageProps.session}>
>               <Component {...pageProps} />
>             </Provider>
>           </ThemeSwitcherProvider>
>         </ApolloProvider>
>       </StoreProvider>
>     </>
>   );
> }
> 
> export default MyApp;
> ```
> 
> What happens is that `defaultTheme` is only evaluated once. In order to change the theme, one must use an effect to react to the value change and trigger a change in `react-css-theme-switcher`
> 
> Cheers 🚀

Thank you 👍 👍
