### ISSUE TITLE
Support Parcel v2

### ISSUE THREAD

**Issue by bhagyas** [JoseRFelix/react-css-theme-switcher#15]
Following path throws an error during builds when using parcel v2 bundler. 

Changing it to `dist/react-css-theme-switcher.esm.js` from `dist/react-theme-switcher.esm.js` seems to fix the issue.

https://github.com/JoseRFelix/react-css-theme-switcher/blob/c622eafb8db5fdb18dea7e267fd517225d2f620d/package.json#L43

**Comment by JoseRFelix** [comment]
Thank you for raising this issue! I will fix this with a new PR.
