### ISSUE TITLE
Flickering while switching  between dark mode theme.

### ISSUE THREAD

**Issue by NeoHBz** [JoseRFelix/react-css-theme-switcher#26]
I'm having 2 versions of dark mode theme and when I switch between them, the screen flickers.
Do we have any fixes so far?

https://user-images.githubusercontent.com/56602090/119228634-7d01e580-bb31-11eb-97e4-33e2c3241a2c.mov

**Comment by JoseRFelix** [comment]
Thanks to @elis we have a fix on this issue. I have published version `0.3.0`. Check it out!
