### ISSUE TITLE
CRA Removing Comments in Production

### ISSUE THREAD

**Issue by mtowercamp** [JoseRFelix/react-css-theme-switcher#5]
is not working on production, but it runs flawlessly in development.

**Comment by JoseRFelix** [comment]
Are you using Create React App?

**Comment by mtowercamp** [comment]
Yes here is my implementation
`index.js`

`const themes = {
  dark: `${process.env.PUBLIC_URL}/dark-theme.css`,
  light: `${process.env.PUBLIC_URL}/light-theme.css`,
};

const isDarkMode = localStorage.getItem("darkMode");

ReactDOM.render(
  <ThemeSwitcherProvider
    themeMap={themes}
    defaultTheme={isDarkMode ? "dark" : "light"}
    insertionPoint="styles-insertion-point"
  >
    <App />
  </ThemeSwitcherProvider>,
  document.getElementById("root")
);`

`App.js`

`import React from "react";
import { BrowserRouter, Switch, Route } from "react-router-dom";
import { LayoutProvider } from "./LayoutContext";
import "./App.css";
import PageLoading from "./components/containers/PageLoading";

const TheLayout = React.lazy(() => import("./containers/TheLayout"));
const Page403 = React.lazy(() => import("./pages/Page403"));
const Page404 = React.lazy(() => import("./pages/Page404"));
const Page500 = React.lazy(() => import("./pages/Page500"));
const Login = React.lazy(() => import("./pages/Login"));

function App() {
  return (
    <BrowserRouter>
      <React.Suspense fallback={<PageLoading />}>
        <Switch>
          <Route
            exact
            path="/login"
            name="Login Page"
            render={(props) => <Login {...props} />}
          />
          <Route
            exact
            path="/403"
            name="Page 403"
            render={(props) => <Page403 {...props} />}
          />
          <Route
            exact
            path="/404"
            name="Page 404"
            render={(props) => <Page404 {...props} />}
          />
          <Route
            exact
            path="/500"
            name="Page 500"
            render={(props) => <Page500 {...props} />}
          />
          <Route
            path="/"
            name="Home"
            render={(props) => (
              <LayoutProvider>
                <TheLayout {...props} />
              </LayoutProvider>
            )}
          />
        </Switch>
      </React.Suspense>
    </BrowserRouter>
  );
}

export default App;`

`App.css`

`.header {
  padding-left: 16px;
  padding-right: 16px;
}

.light-header {
  background-color: #ffffff;
}

.side-logo {
  padding-left: 24px;
  padding-top: 16px;
  padding-bottom: 16px;
}

.content {
  padding: 20px;
}

.sidebar::-webkit-scrollbar,
.ant-drawer-body::-webkit-scrollbar {
  width: 3px;
}

.sidebar::-webkit-scrollbar-track,
.ant-drawer-body::-webkit-scrollbar-track {
  background: #f1f1f1;
}

.sidebar::-webkit-scrollbar-thumb,
.ant-drawer-body::-webkit-scrollbar-thumb {
  background: #00adb5;
}

.sidebar::-webkit-scrollbar-thumb:hover,
.ant-drawer-body::-webkit-scrollbar-thumb:hover {
  background: #00f2ff;
}

.clickable {
  cursor: pointer;
}

.page-loading {
  text-align: center;
  margin: 20px 0;
}
`

`index.html`

`
<title>React App</title>
    
  </head>
  <body>`

**Comment by JoseRFelix** [comment]
Is the console logging any errors?

**Comment by mtowercamp** [comment]
None, I guess the comment `<!--styles-insertion-point-->` doesn't compiled during `npm run build`

**Comment by mtowercamp** [comment]
> Is the console logging any errors?

Insertion point 'styles-insertion-point' does not exist. Be sure to add comment on head and that it matches the insertionPoint

**Comment by mtowercamp** [comment]
I guess it is not compiled during `npm run build`

**Comment by JoseRFelix** [comment]
This happens because your production build is removing the comments in your `index.html`. Seems to be that CRA has added an update that does this automatically. I will be working on a fix for this. As a workaround, you can create a comment in your code and append it to the `document`:

```
const styleNode = document.createComment('style-insertion-point');
document.head.insertBefore(styleNode, document.head.firstChild);
```

This snippet should only be run once so `index.js` would be a place to put it.

**Comment by mtowercamp** [comment]
It works thank you so much.

**Comment by EndermanAPM** [comment]
I would like to point out (just in case someone has the same silly mistake as me) that the [blog post](https://jfelix.info/blog/dynamic-themes-in-ant-design-how-to-change-between-light-and-dark-theme) uses `<!--styles-insertion-point-->` as the insertion point and the example workaround code uses `style-insertion-point` (singular).

Ps. Would you be interested in a pr with a possible fix?

**Comment by EndermanAPM** [comment]
So, it's this fix? What is the fix? Just use the workaround?

**Comment by JoseRFelix** [comment]
I fixed it on the latest release! Now we can use [DOM elements as insertion point](https://github.com/JoseRFelix/react-css-theme-switcher#html-element-insertion-point). :rocket:

**Comment by EndermanAPM** [comment]
Awesome, thanks!
