### ISSUE TITLE
Change Primary Color [Theme Color]

### ISSUE THREAD

**Issue by mtowercamp** [JoseRFelix/react-css-theme-switcher#7]
How to change primary color dynamically during runtime in ant design using the this react-css-theme-switcher

**Comment by JoseRFelix** [comment]
This library is meant for only changing pre-built themes. If you want to change colors dynamically you can generate a theme for each of the colors that you need. 

On the other hand, these libraries allow for switching colors on runtime which can be CPU demanding: [dynamic-antd-theme](https://github.com/luffyZh/dynamic-antd-theme) or [react-app-rewire-antd-theme](https://github.com/mzohaibqc/react-app-rewire-antd-theme).
