### ISSUE TITLE
Need of working example

### ISSUE THREAD

**Issue by GeorgeCodeHub** [JoseRFelix/react-css-theme-switcher#8]
I'm trying to set up your package on my application but for some reason it doesn't import my CSS files. Do you have a working example that you could share?

Here is where I am right now.

https://stackblitz.com/edit/react-theme-switch

**Comment by JoseRFelix** [comment]
Check this sandbox: [codesandbox.io/s/react-css-theme-switcher-cra-oel5h](https://codesandbox.io/s/react-css-theme-switcher-cra-oel5h). Let me know if it solved your problem.

**Comment by GeorgeCodeHub** [comment]
That's exactly what I needed. Thank you! One more question. Is it possible to pass more than one css file in the theme option? 

Example:

const themes = {
  light: [`light_part1.css`,`light_part2.css`]
  dark: `dark.css`
};

**Comment by JoseRFelix** [comment]
No. But you can create another key for it!

```
const themes = {
	light-part-1: "light_part1.css",
	light-part-2: "light_part2.css",
	dark: "dark.css"
};
```

**Comment by GeorgeCodeHub** [comment]
Thank you very much!
