### ISSUE TITLE
How to use it with Babel and Webpack

### ISSUE THREAD

**Issue by Woong25** [JoseRFelix/react-css-theme-switcher#9]
I am using antd by importing to Babel and implemented dark mode using this package.
```
// .babelrc
"plugins": [
    [
      "import", {
        "libraryName": "antd",
        "style": "css"
      }
    ],
]
```
It works fine, but the problem goes back to the default style after a while.
Maybe it's using a Babel.

even use next.js and the code seems to need to be set up because it is splitting.

Is there any way to solve this problem?

**Comment by JoseRFelix** [comment]
The way to solve this is by removing AntD babel plugin altogether, and load a CSS file for each theme. What is happening in your site is that the library's code is conflicting with Babel CSS insertions, so you have to add AntD CSS through `react-css-theme-switcher` itself.

**Comment by Woong25** [comment]
Hello @JoseRFelix 
thank you for the reply.

I would like to implement it so that the color changes when the theme changes. Like youtube

However, if remove babel, the style is broken at the moment when the theme is being changed, so i need to implement loading.

Can't the style be broken when changing the theme?

**Comment by hadnet** [comment]
Is there a way I can use this package using Next.Js instead?

**Comment by hadnet** [comment]
I'm using Next.js with it but the problem is I lose state transition between light to dark mode. For example, if I use the antd switch component with the onChange prop my switch got stuck. Is this issue something related because I'm using with Next.js?

**Comment by JoseRFelix** [comment]
> Hello @JoseRFelix
> thank you for the reply.
> 
> I would like to implement it so that the color changes when the theme changes. Like youtube
> 
> However, if remove babel, the style is broken at the moment when the theme is being changed, so i need to implement loading.
> 
> Can't the style be broken when changing the theme?

What do you mean by breaking the style down? 

If you want to change colors dynamically, the best-case scenario would be to have CSS variables, but this is not possible in some implementations like AntD. However, you can generate a stylesheet for every color and change between them with `react-css-theme-switcher`. The library is pretty performant since stylesheets are preloaded.

**Comment by JoseRFelix** [comment]
> I'm using Next.js with it but the problem is I lose state transition between light to dark mode. For example, if I use the antd switch component with the onChange prop my switch got stuck. Is this issue something related because I'm using with Next.js?

Next.js should not conflict with `react-css-theme-switcher`. The `Provider` has to wrap `Component` on `_app.js`, so it does not get unmounted with the page. Like this:

```
const App = () => {
  return (
    <ThemeSwitcherProvider
      defaultTheme="light"
      insertionPoint="inject-styles-here"
      themeMap={themes}
    >
      <Component />
    </ThemeSwitcherProvider>
  );
};
```
